<div class="grid delivery-kpis">
<div class="stat"><small>Total orders — {{ $calendarMonth->format('F Y') }}</small><strong>{{ $stats['month_total'] }}</strong></div>
<a class="stat danger-stat" href="{{ route('deliveries.index',['scope'=>'overdue','month'=>$calendarMonth->format('Y-m')]) }}"><small>Overdue</small><strong>{{ $stats['overdue'] }}</strong></a>
<div class="stat waiting-stat"><small>Waiting deposit</small><strong>{{ $stats['waiting_deposit'] }}</strong></div>
<div class="stat design-stat"><small>Need design — overdue + next 10 days</small><strong>{{ $stats['need_design'] }}</strong></div>
</div>
<section class="card delivery-workspace">
<form method="get" class="delivery-main-filters"><input type="hidden" name="month" value="{{ $calendarMonth->format('Y-m') }}"><label>Date<input type="date" name="date" value="{{ request('date') }}"></label><label>Delivery location<select name="location"><option value="">All locations</option>@foreach($locations as $location)<option value="{{ $location }}" @selected(request('location')===$location)>{{ $location }}</option>@endforeach</select></label><label class="delivery-search">Search<input name="q" value="{{ request('q') }}" placeholder="Order, customer, phone, area or address"></label><button class="btn primary">Apply</button><a class="btn" href="{{ route('deliveries.index',['month'=>$calendarMonth->format('Y-m')]) }}">Reset</a></form>
<nav class="delivery-tabs"><a @class(['active'=>!request('scope')||request('scope')==='working']) href="{{ route('deliveries.index',array_filter(['scope'=>'working','month'=>$calendarMonth->format('Y-m'),'date'=>request('date'),'location'=>request('location'),'q'=>request('q')])) }}">Working list</a><a @class(['active'=>request('scope')==='overdue']) href="{{ route('deliveries.index',['scope'=>'overdue','month'=>$calendarMonth->format('Y-m')]) }}">Overdue ({{ $stats['overdue'] }})</a><a @class(['active'=>request('scope')==='today']) href="{{ route('deliveries.index',['scope'=>'today','month'=>$calendarMonth->format('Y-m')]) }}">Today</a><a @class(['active'=>request('scope')==='all']) href="{{ route('deliveries.index',['scope'=>'all','month'=>$calendarMonth->format('Y-m')]) }}">All orders</a><span class="live-indicator"><i></i>Updates automatically every 12 seconds</span></nav>
<div class="table-wrap delivery-dashboard-table"><table><thead><tr><th>Priority</th><th>Order</th><th>Customer</th><th>Date</th><th>Location / Area</th><th>Confirmation</th><th>Design</th><th>Driver</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($deliveries as $delivery)
@php
$order=$delivery->salesOrder;$customer=$delivery->customer;$overdue=$delivery->delivery_date&&$delivery->delivery_date->isBefore(today())&&!in_array($delivery->status,['delivered','returned']);$days=$overdue?$delivery->delivery_date->diffInDays(today()):($delivery->delivery_date?->diffInDays(today(),false));$phone=$order->customer_phone?:$customer->phone;$area=$customer->area;$address=$order->delivery_address?:$customer->delivery_address;
@endphp
<tr @class(['overdue-row'=>$overdue,'very-urgent-row'=>$order->is_very_urgent])>
<td data-label="Priority">@if($order->is_very_urgent)<span class="priority-box urgent">●<b>Very urgent</b><small>{{ $overdue?$days.' days past':($delivery->delivery_date?->isToday()?'Today':abs((int)$days).' days left') }}</small></span>@elseif($overdue)<span class="priority-box overdue">⏱<b>{{ $days }} days past</b></span>@else<span class="priority-box"><b>{{ ucfirst($order->priority) }}</b><small>{{ $delivery->delivery_date?->isToday()?'Today':abs((int)$days).' days left' }}</small></span>@endif</td>
<td data-label="Order"><a href="{{ route('orders.show',$order) }}"><b>#{{ $order->order_number }}</b></a><small>{{ $order->is_legacy_delivery_import?'Imported history':'Manual · '.$order->order_month?->format('M Y') }}</small></td>
<td data-label="Customer"><b>{{ $customer->name }}</b><small>{{ $phone?:'No phone' }}</small></td>
<td data-label="Date"><b>{{ $delivery->delivery_date?->format('d M')??'Not set' }}</b><small>{{ $delivery->delivery_date?->format('Y') }}</small></td>
<td data-label="Location"><b>{{ $order->emirate?:$customer->emirate?:'Not set' }}</b><small title="{{ $address }}">{{ $area?str($area)->limit(25):str($address)->limit(34) }}</small></td>
<td data-label="Confirmation">@if(!$isDriverOnly)<form method="post" action="{{ route('deliveries.quick-update',$delivery) }}">@csrf @method('patch')<select name="confirmation_status" class="mini-status" onchange="this.form.submit()"><option value="waiting" @selected($order->confirmation_status==='waiting')>Waiting</option><option value="waiting_for_deposit" @selected($order->confirmation_status==='waiting_for_deposit')>Waiting deposit</option><option value="confirmed" @selected($order->confirmation_status==='confirmed')>Confirmed</option><option value="cancelled" @selected($order->confirmation_status==='cancelled')>Cancelled</option></select></form>@else<span class="badge">{{ str($order->confirmation_status)->replace('_',' ') }}</span>@endif</td>
<td data-label="Design">@if(!$isDriverOnly)<form method="post" action="{{ route('deliveries.quick-update',$delivery) }}">@csrf @method('patch')<select name="design_status" class="mini-status" onchange="this.form.submit()"><option value="need_design" @selected($order->design_status==='need_design')>Need design</option><option value="designing" @selected($order->design_status==='designing')>Designing</option><option value="waiting_customer" @selected($order->design_status==='waiting_customer')>Waiting customer</option><option value="designed" @selected($order->design_status==='designed')>Designed</option></select></form>@else<span class="badge">{{ str($order->design_status)->replace('_',' ') }}</span>@endif</td>
<td data-label="Driver">@if(!$isDriverOnly)<form method="post" action="{{ route('deliveries.quick-update',$delivery) }}">@csrf @method('patch')<select name="driver_id" class="mini-status" onchange="this.form.submit()"><option value="">Unassigned</option>@foreach($drivers as $driver)<option value="{{ $driver->id }}" @selected($delivery->driver_id===$driver->id)>{{ $driver->name }}</option>@endforeach</select></form>@else{{ $delivery->driver?->name??'Unassigned' }}@endif</td>
<td data-label="Status">@if(!$isDriverOnly)<form method="post" action="{{ route('deliveries.quick-update',$delivery) }}">@csrf @method('patch')<select name="status" class="mini-status delivery-state" onchange="this.form.submit()">@foreach(['pending','out_for_delivery','delivered','partial','failed','returned'] as $status)<option value="{{ $status }}" @selected($delivery->status===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></form>@else<span class="badge">{{ str($delivery->status)->replace('_',' ') }}</span>@endif</td>
<td data-label="Actions"><div class="row-actions"><a class="btn small" href="{{ route('deliveries.show',$delivery) }}" title="Delivery details">Delivery</a>@if(!$order->is_legacy_delivery_import&&auth()->user()->hasPermission('orders.manage'))<a class="btn small primary" href="{{ route('orders.edit',$order) }}">Edit order</a>@endif</div></td>
</tr>
@empty<tr><td colspan="10" class="empty">No deliveries match these filters.</td></tr>@endforelse
</tbody></table></div>{{ $deliveries->links() }}
</section>
