@extends('layouts.app')
@section('title',$customer->exists?'Edit Customer':'New Customer')
@section('subtitle','Customer code is generated automatically — enter the name, phone and delivery details')
@section('content')
<form method="post" action="{{ $customer->exists?route('customers.update',$customer):route('customers.store') }}">@csrf @if($customer->exists)@method('put')@endif
<div class="card"><div class="form-grid">
<label>Name<input name="name" value="{{ old('name',$customer->name) }}" required></label><label>Company<input name="company_name" value="{{ old('company_name',$customer->company_name) }}"></label><label>Phone<input name="phone" value="{{ old('phone',$customer->phone) }}" placeholder="+971..."></label><label>WhatsApp<input name="whatsapp" value="{{ old('whatsapp',$customer->whatsapp) }}" placeholder="+971..."></label><label>Email<input type="email" name="email" value="{{ old('email',$customer->email) }}"></label><label>TRN<input name="trn" value="{{ old('trn',$customer->trn) }}"></label>
<label>Delivery location<select name="emirate"><option value="">Select</option>@foreach(['Abu Dhabi','Dubai','Sharjah','Ajman','Umm Al Quwain','Ras Al Khaimah','Fujairah','Western Region','Personal Pickup','Saudi Arabia','Oman','Qatar','Kuwait','Bahrain','Other GCC'] as $value)<option value="{{ $value }}" @selected(old('emirate',$customer->emirate)===$value)>{{ $value }}</option>@endforeach</select></label><label>Area<input name="area" value="{{ old('area',$customer->area) }}"></label>
<label>Language<select name="preferred_language"><option value="en" @selected(old('preferred_language',$customer->preferred_language?:'en')==='en')>English</option><option value="ar" @selected(old('preferred_language',$customer->preferred_language)==='ar')>Arabic</option></select></label><label>Type<select name="customer_type"><option value="retail" @selected(old('customer_type',$customer->customer_type?:'retail')==='retail')>Retail</option><option value="corporate" @selected(old('customer_type',$customer->customer_type)==='corporate')>Corporate</option></select></label><label>Source<input name="source" value="{{ old('source',$customer->source) }}"></label><label>Payment terms (days)<input type="number" name="payment_terms_days" min="0" value="{{ old('payment_terms_days',$customer->payment_terms_days??0) }}"></label><label>Credit limit<input type="number" step="0.01" min="0" name="credit_limit" value="{{ old('credit_limit',$customer->credit_limit??0) }}"></label><label>Status<select name="status"><option value="active" @selected(old('status',$customer->status?:'active')==='active')>Active</option><option value="inactive" @selected(old('status',$customer->status)==='inactive')>Inactive</option><option value="blocked" @selected(old('status',$customer->status)==='blocked')>Blocked</option></select></label>
<label class="span-2">Billing address<textarea name="billing_address">{{ old('billing_address',$customer->billing_address) }}</textarea></label><label class="span-2">Delivery address<textarea name="delivery_address">{{ old('delivery_address',$customer->delivery_address) }}</textarea></label><label class="span-2">Notes<textarea name="notes">{{ old('notes',$customer->notes) }}</textarea></label>
</div><div class="actions"><a class="btn" href="{{ route('customers.index') }}">Cancel</a><button class="btn primary">Save customer</button></div></div></form>
@endsection
