@extends('layouts.app') @section('title',$quotation->exists?'Edit Quotation':'New Quotation') @section('subtitle','UAE VAT is calculated from each line item')
@section('content')
@php
$savedLines=$quotation->exists?$quotation->items->map(fn($item)=>['product_id'=>$item->product_id,'product_label'=>$item->product?($item->product->name_en.($item->product->sku?' · '.$item->product->sku:'')):null,'description'=>$item->description,'qty'=>$item->qty,'unit_price'=>$item->unit_price,'discount'=>$item->discount,'tax_rate'=>$item->tax_rate,'is_manual'=>!$item->product_id])->all():[['product_id'=>'','product_label'=>null,'description'=>'','qty'=>1,'unit_price'=>0,'discount'=>0,'tax_rate'=>5,'is_manual'=>false]];
$lines=old('items',$savedLines);
@endphp
<form method="post" action="{{ $quotation->exists?route('quotations.update',$quotation):route('quotations.store') }}" data-quotation-form data-quick-customer="{{ route('orders.quick-customer') }}" data-quick-product="{{ route('orders.quick-product') }}" data-customer-search-url="{{ route('orders.search-customers') }}" data-product-search-url="{{ route('orders.search-products') }}">@csrf @if($quotation->exists)@method('put')@endif
<div class="card"><div class="form-grid">
<label class="span-2">Customer
  <div class="combo-input-row">
    <div class="combo">
      <input type="text" data-customer-combo-input autocomplete="off" placeholder="Type name or phone to search..." name="customer_label" value="{{ old('customer_label', $quotation->exists && $quotation->customer ? $quotation->customer->name.($quotation->customer->phone?' · '.$quotation->customer->phone:'') : '') }}" required>
      <div class="combo-results" data-customer-combo-results></div>
    </div>
    <input type="hidden" name="customer_id" data-customer-combo-id value="{{ old('customer_id',$quotation->customer_id) }}">
    <button type="button" class="btn" data-open-dialog="quick-customer">+ Add customer</button>
  </div>
</label>
<label>Status<select name="status"><option value="draft" @selected(old('status',$quotation->status??'draft')==='draft')>draft</option><option value="sent" @selected(old('status',$quotation->status)==='sent')>sent</option><option value="approved" @selected(old('status',$quotation->status)==='approved')>approved</option></select></label>
<label>Quotation date<input type="date" name="quotation_date" value="{{ old('quotation_date',$quotation->quotation_date?->format('Y-m-d')??today()->toDateString()) }}" required></label>
<label>Valid until<input type="date" name="valid_until" value="{{ old('valid_until',$quotation->valid_until?->format('Y-m-d')??today()->addDays(14)->toDateString()) }}"></label>
</div></div>
<div class="card" style="margin-top:18px"><div class="card-header"><h2>Items</h2><div class="header-actions"><button type="button" class="btn small" data-add-row>+ Add product</button><button type="button" class="btn small" data-add-manual-row>+ Add manual line</button><button type="button" class="btn small" data-open-dialog="quick-product">+ New product</button></div></div>
<div class="table-wrap items-table-wrap"><table id="quote-items"><thead><tr><th>Product</th><th>Qty</th><th>Unit price</th><th>Discount</th><th>VAT %</th><th>Total</th><th></th></tr></thead><tbody>
@foreach($lines as $index=>$line)
@if($line['is_manual']??false)
<tr data-product-row><td><input type="text" name="items[{{ $index }}][description]" value="{{ $line['description']??'' }}" placeholder="Description (e.g. Fixing charge)" required><input type="hidden" name="items[{{ $index }}][product_id]" value=""></td><td><input data-qty type="number" step="0.001" min="0.001" name="items[{{ $index }}][qty]" value="{{ $line['qty']??1 }}" required></td><td><input data-price type="number" step="0.01" min="0" name="items[{{ $index }}][unit_price]" value="{{ $line['unit_price']??0 }}" required></td><td><input data-discount type="number" step="0.01" min="0" name="items[{{ $index }}][discount]" value="{{ $line['discount']??0 }}"></td><td><input data-tax type="number" step="0.01" min="0" name="items[{{ $index }}][tax_rate]" value="{{ $line['tax_rate']??5 }}"></td><td class="amount" data-line-total>0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr>
@else
<tr data-product-row><td><div class="combo-input-row"><div class="combo"><input type="text" data-product-combo-input autocomplete="off" placeholder="Search name or SKU..." name="items[{{ $index }}][product_label]" value="{{ $line['product_label']??'' }}" required><div class="combo-results" data-product-combo-results></div></div><input type="hidden" name="items[{{ $index }}][product_id]" data-product-combo-id value="{{ $line['product_id']??'' }}"></div></td><td><input data-qty type="number" step="0.001" min="0.001" name="items[{{ $index }}][qty]" value="{{ $line['qty']??1 }}" required></td><td><input data-price type="number" step="0.01" min="0" name="items[{{ $index }}][unit_price]" value="{{ $line['unit_price']??0 }}" required></td><td><input data-discount type="number" step="0.01" min="0" name="items[{{ $index }}][discount]" value="{{ $line['discount']??0 }}"></td><td><input data-tax type="number" step="0.01" min="0" name="items[{{ $index }}][tax_rate]" value="{{ $line['tax_rate']??5 }}"></td><td class="amount" data-line-total>0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr>
@endif
@endforeach
</tbody>
<template data-row-template><tr data-product-row><td><div class="combo-input-row"><div class="combo"><input type="text" data-product-combo-input autocomplete="off" placeholder="Search name or SKU..." name="items[__INDEX__][product_label]" required><div class="combo-results" data-product-combo-results></div></div><input type="hidden" name="items[__INDEX__][product_id]" data-product-combo-id value=""></div></td><td><input data-qty type="number" step="0.001" min="0.001" name="items[__INDEX__][qty]" value="1" required></td><td><input data-price type="number" step="0.01" min="0" name="items[__INDEX__][unit_price]" value="0" required></td><td><input data-discount type="number" step="0.01" min="0" name="items[__INDEX__][discount]" value="0"></td><td><input data-tax type="number" step="0.01" min="0" name="items[__INDEX__][tax_rate]" value="5"></td><td class="amount" data-line-total>0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr></template>
<template data-manual-row-template><tr data-product-row><td><input type="text" name="items[__INDEX__][description]" placeholder="Description (e.g. Fixing charge)" required><input type="hidden" name="items[__INDEX__][product_id]" value=""></td><td><input data-qty type="number" step="0.001" min="0.001" name="items[__INDEX__][qty]" value="1" required></td><td><input data-price type="number" step="0.01" min="0" name="items[__INDEX__][unit_price]" value="0" required></td><td><input data-discount type="number" step="0.01" min="0" name="items[__INDEX__][discount]" value="0"></td><td><input data-tax type="number" step="0.01" min="0" name="items[__INDEX__][tax_rate]" value="5"></td><td class="amount" data-line-total>0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr></template>
</table></div>
<div class="summary" style="margin-top:15px"><div><small>Subtotal</small><strong>AED <span data-subtotal>0.00</span></strong></div><div><small>Discount</small><strong>AED <span data-discount-total>0.00</span></strong></div><div><small>VAT</small><strong>AED <span data-tax-total>0.00</span></strong></div><div><small>Grand total</small><strong>AED <span data-grand-total>0.00</span></strong></div></div>
<label style="margin-top:15px">Terms / notes<textarea name="notes">{{ old('notes',$quotation->notes) }}</textarea></label><div class="actions"><a class="btn" href="{{ route('quotations.index') }}">Cancel</a><button class="btn primary">{{ $quotation->exists?'Update quotation':'Create quotation' }}</button></div></div></form>

<dialog id="quick-customer" class="quick-dialog"><form data-quick-customer-form><div class="dialog-head"><h2>Add customer</h2><button type="button" class="dialog-close" data-close-dialog>×</button></div><div class="form-grid"><label>Name<input name="name" required></label><label>Phone<input name="phone" placeholder="+971..." required></label><label>Location<select name="emirate"><option value="">Select</option>@foreach($locations as $location)<option>{{ $location }}</option>@endforeach</select></label><label>Area<input name="area"></label><label class="span-2">Delivery address<textarea name="delivery_address"></textarea></label></div><p class="form-error" data-form-error></p><div class="actions"><button type="button" class="btn" data-close-dialog>Cancel</button><button type="submit" class="btn primary">Save and select</button></div></form></dialog>
<dialog id="quick-product" class="quick-dialog"><form data-quick-product-form enctype="multipart/form-data"><div class="dialog-head"><h2>Add product</h2><button type="button" class="dialog-close" data-close-dialog>×</button></div><div class="form-grid">@include('products._fields', ['product' => new \App\Models\Product, 'categories' => $productCategories ?? collect(), 'taxRates' => $productTaxRates ?? collect(), 'fieldPrefix' => null])</div><p class="form-error" data-form-error></p><div class="actions"><button type="button" class="btn" data-close-dialog>Cancel</button><button type="submit" class="btn primary">Save and select</button></div></form></dialog>
@endsection
@push('scripts')<script src="{{ asset('build/assets/order-entry.js') }}?v={{ @filemtime(public_path('build/assets/order-entry.js')) ?: time() }}" defer></script>@endpush
