<?php
namespace App\Http\Controllers;
use App\Models\{Customer,DeliveryNote,Invoice,Product,SalesOrder};
use App\Services\{NumberingService,PhoneNormalizer};
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;
class ImportExportController extends Controller
{
    public function index(){return view('system.import-export');}
    public function export(string $type): StreamedResponse
    {
        abort_unless(in_array($type,['customers','orders','invoices','deliveries']),404);$name="ivory-{$type}-".today()->format('Y-m-d').'.csv';return response()->streamDownload(function()use($type){$out=fopen('php://output','w');fputs($out,"\xEF\xBB\xBF");if($type==='customers'){fputcsv($out,['Code','Name','Company','Phone','WhatsApp','Email','Emirate','Area','Status']);Customer::orderBy('id')->chunk(500,fn($rows)=>$rows->each(fn($r)=>fputcsv($out,[$r->customer_code,$r->name,$r->company_name,$r->phone,$r->whatsapp,$r->email,$r->emirate,$r->area,$r->status])));}if($type==='orders'){fputcsv($out,['Order','Customer','Date','Delivery date','Emirate','Confirmation','Design','Production','Delivery','Payment','Total']);SalesOrder::with('customer')->where('is_legacy_delivery_import',false)->chunk(500,fn($rows)=>$rows->each(fn($r)=>fputcsv($out,[$r->order_number,$r->customer->name,$r->order_date,$r->delivery_date,$r->emirate,$r->confirmation_status,$r->design_status,$r->production_status,$r->delivery_status,$r->payment_status,$r->grand_total])));}if($type==='invoices'){fputcsv($out,['Invoice','Customer','Date','Due','Status','Total','Paid','Outstanding']);Invoice::with('customer')->chunk(500,fn($rows)=>$rows->each(fn($r)=>fputcsv($out,[$r->invoice_number,$r->customer->name,$r->invoice_date,$r->due_date,$r->status,$r->grand_total,$r->amount_paid,$r->outstanding_amount])));}if($type==='deliveries'){fputcsv($out,['Delivery note','Order','Customer','Date','Status','Delivered at']);DeliveryNote::with('customer','salesOrder')->chunk(500,fn($rows)=>$rows->each(fn($r)=>fputcsv($out,[$r->delivery_note_number,$r->salesOrder->order_number,$r->customer->name,$r->delivery_date,$r->status,$r->delivered_at])));}fclose($out);},$name,['Content-Type'=>'text/csv; charset=UTF-8']);
    }
    public function import(Request $r,NumberingService $numbers,PhoneNormalizer $phones){$d=$r->validate(['type'=>'required|in:customers,products','file'=>'required|file|mimes:csv,txt|max:10240']);$handle=fopen($d['file']->getRealPath(),'r');$headers=array_map(fn($h)=>strtolower(trim($h)),fgetcsv($handle));$processed=0;$errors=[];while(($row=fgetcsv($handle))!==false){$data=array_combine($headers,array_pad($row,count($headers),null));try{if($d['type']==='customers'){Customer::updateOrCreate(['customer_code'=>$data['customer_code']??$numbers->next('customer')],['name'=>$data['name'],'company_name'=>$data['company_name']??null,'phone'=>$phones->normalize($data['phone']??null),'whatsapp'=>$phones->normalize($data['whatsapp']??$data['phone']??null),'email'=>$data['email']??null,'emirate'=>$data['emirate']??null,'area'=>$data['area']??null,'status'=>$data['status']??'active','created_by'=>auth()->id(),'updated_by'=>auth()->id()]);}else{Product::updateOrCreate(['sku'=>$data['sku']],['name_en'=>$data['name_en']??$data['name'],'name_ar'=>$data['name_ar']??null,'sale_price'=>$data['sale_price']??0,'cost_price'=>$data['cost_price']??0,'unit'=>$data['unit']??'piece','is_active'=>true]);}$processed++;}catch(\Throwable $e){$errors[]='Row '.($processed+count($errors)+2).': '.$e->getMessage();if(count($errors)>=20)break;}}fclose($handle);return back()->with('success',"Imported {$processed} rows.")->with('import_errors',$errors);}
}
