<?php
namespace App\Http\Controllers;
use App\Models\{ProductionJob,SalesOrderStatusHistory,User};
use Illuminate\Http\Request;
class ProductionController extends Controller
{
    public function index(){ $q=ProductionJob::with('salesOrder.customer','designer');if(request('stage'))$q->where('stage',request('stage'));return view('production.index',['jobs'=>$q->orderBy('due_date')->paginate(30),'staff'=>User::where('is_active',true)->get()]);}
    public function update(Request $r,ProductionJob $job){$d=$r->validate(['stage'=>'required|in:waiting_for_design,designing,waiting_customer,approved,materials_pending,in_production,quality_check,ready,completed,cancelled','designer_id'=>'nullable|exists:users,id','production_staff_id'=>'nullable|exists:users,id','due_date'=>'nullable|date','notes'=>'nullable|string','cost_type'=>'nullable|in:materials,labour,outsourced,transport,other','cost_amount'=>'nullable|numeric|min:0','cost_description'=>'nullable|string']);$job->update(collect($d)->only(['stage','designer_id','production_staff_id','due_date','notes'])->all());if(!empty($d['cost_amount']))$job->costs()->create(['cost_type'=>$d['cost_type']??'other','amount'=>$d['cost_amount'],'description'=>$d['cost_description']??null]);$job->total_cost=$job->costs()->sum('amount');$job->actual_profit=(float)$job->sale_value-(float)$job->total_cost;$job->save();$map=['waiting_for_design'=>'waiting','designing'=>'waiting','waiting_customer'=>'waiting','approved'=>'materials_pending','materials_pending'=>'materials_pending','in_production'=>'in_production','quality_check'=>'quality_check','ready'=>'ready','completed'=>'completed'];$job->salesOrder->update(['production_status'=>$map[$d['stage']]??$job->salesOrder->production_status,'design_status'=>in_array($d['stage'],['approved','materials_pending','in_production','quality_check','ready','completed'])?'designed':($d['stage']==='designing'?'designing':$job->salesOrder->design_status)]);return back()->with('success','Production job updated.');}
}
