<?php
namespace App\Http\Controllers;
use App\Models\{Product,PurchaseOrder,StockItem,Supplier,Warehouse};
use App\Services\{DocumentTotals,NumberingService};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
class PurchaseOrderController extends Controller
{
    public function index(){return view('purchases.index',['orders'=>PurchaseOrder::with('supplier')->latest()->paginate(25),'suppliers'=>Supplier::where('status','active')->get(),'products'=>Product::where('is_active',true)->get()]);}
    public function store(Request $r,NumberingService $n,DocumentTotals $totals){$d=$r->validate(['supplier_id'=>'required|exists:suppliers,id','order_date'=>'required|date','expected_delivery_date'=>'nullable|date','notes'=>'nullable|string','items'=>'required|array|min:1','items.*.product_id'=>'required|exists:products,id','items.*.qty'=>'required|numeric|min:0.001','items.*.unit_cost'=>'required|numeric|min:0','items.*.tax_rate'=>'nullable|numeric|min:0|max:100']);$mapped=array_map(fn($i)=>$i+['unit_price'=>$i['unit_cost']],$d['items']);$calc=$totals->calculate($mapped);$po=DB::transaction(function()use($d,$calc,$n){$po=PurchaseOrder::create(['purchase_order_number'=>$n->next('purchase_order'),'supplier_id'=>$d['supplier_id'],'order_date'=>$d['order_date'],'expected_delivery_date'=>$d['expected_delivery_date']??null,'status'=>'draft','subtotal'=>$calc['subtotal'],'tax_total'=>$calc['tax_total'],'grand_total'=>$calc['grand_total'],'notes'=>$d['notes']??null]);foreach($calc['items'] as $i){$p=Product::find($i['product_id']);$po->items()->create(['product_id'=>$p->id,'description'=>$p->name_en,'qty'=>$i['qty'],'unit_cost'=>$i['unit_price'],'tax_amount'=>$i['tax_amount'],'line_total'=>$i['line_total']]);}return $po;});return back()->with('success',"Purchase order {$po->purchase_order_number} created.");}
    public function receive(PurchaseOrder $purchaseOrder){if($purchaseOrder->status==='received')return back()->withErrors(['purchase'=>'Already received.']);DB::transaction(function()use($purchaseOrder){$warehouse=Warehouse::firstOrCreate(['name'=>'Main Warehouse'],['is_active'=>true]);foreach($purchaseOrder->items as $i){$stock=StockItem::firstOrCreate(['product_id'=>$i->product_id,'warehouse_id'=>$warehouse->id]);$oldQty=(float)$stock->quantity_on_hand;$newQty=$oldQty+(float)$i->qty;$stock->weighted_average_cost=$newQty>0?(($oldQty*(float)$stock->weighted_average_cost)+((float)$i->qty*(float)$i->unit_cost))/$newQty:(float)$i->unit_cost;$stock->quantity_on_hand=$newQty;$stock->save();$stock->movements()->create(['type'=>'receipt','quantity_delta'=>$i->qty,'unit_cost'=>$i->unit_cost,'reference_type'=>PurchaseOrder::class,'reference_id'=>$purchaseOrder->id,'movement_date'=>now(),'created_by'=>auth()->id()]);}$purchaseOrder->update(['status'=>'received']);});return back()->with('success','Stock received and inventory updated.');}
}
