@extends('layouts.app')
@section('title',$order->exists?'Edit Sales Order '.$order->order_number:'New Sales Order')
@section('subtitle','The selected delivery date automatically places this order in the delivery schedule')
@section('content')
@php
$savedLines=$order->exists?$order->items->map(fn($item)=>['product_id'=>$item->product_id,'product_label'=>$item->product?($item->product->name_en.($item->product->sku?' · '.$item->product->sku:'')):null,'description'=>$item->description,'qty'=>$item->qty,'unit_price'=>$item->unit_price,'tax_rate'=>($item->qty*$item->unit_price)>0?round($item->tax_amount/($item->qty*$item->unit_price)*100,2):0,'customisation'=>$item->customisation['notes']??'','is_manual'=>!$item->product_id])->all():[['product_id'=>'','product_label'=>null,'description'=>'','qty'=>1,'unit_price'=>0,'tax_rate'=>5,'customisation'=>'','is_manual'=>false]];
$lines=old('items',$savedLines);
@endphp
<form method="post" action="{{ $order->exists?route('orders.update',$order):route('orders.store') }}" data-order-form data-is-new-order="{{ $order->exists?'0':'1' }}" data-quick-customer="{{ route('orders.quick-customer') }}" data-quick-product="{{ route('orders.quick-product') }}" data-customer-search-url="{{ route('orders.search-customers') }}" data-product-search-url="{{ route('orders.search-products') }}">@csrf @if($order->exists)@method('put')@endif
<div class="card"><div class="form-grid">
<label class="span-2">Customer
  <div class="combo-input-row">
    <div class="combo">
      <input type="text" data-customer-combo-input autocomplete="off" placeholder="Type name or phone to search..." name="customer_label" value="{{ old('customer_label', $order->exists && $order->customer ? $order->customer->name.($order->customer->phone?' · '.$order->customer->phone:'') : '') }}" required>
      <div class="combo-results" data-customer-combo-results></div>
    </div>
    <input type="hidden" name="customer_id" data-customer-combo-id value="{{ old('customer_id',$order->customer_id) }}">
    <button type="button" class="btn" data-open-dialog="quick-customer">+ Add customer</button>
  </div>
</label>
<label>Phone number<input name="customer_phone" data-customer-phone value="{{ old('customer_phone',$order->customer_phone) }}" placeholder="+971..."></label>
<label>Order Number<input name="manual_reference" data-manual-reference value="{{ old('manual_reference',$order->manual_reference) }}" maxlength="10" required @if($order->exists) readonly title="Set once at creation, part of the permanent order number" @endif></label>
<label>Order date<input type="date" name="order_date" data-order-date value="{{ old('order_date',$order->order_date?->toDateString()??today()->toDateString()) }}" required></label>
<label>Final order number<output data-final-order-number>{{ $order->exists ? $order->order_number : '—' }}</output></label>
<label>Delivery date<input type="date" name="delivery_date" data-capacity-check value="{{ old('delivery_date',$order->delivery_date?->toDateString()) }}" required><small data-capacity-message></small></label>
<label>Delivery location<select name="emirate" data-customer-location required><option value="">Select location</option>@foreach($locations as $location)<option value="{{ $location }}" @selected(old('emirate',$order->emirate)===$location)>{{ $location }}</option>@endforeach</select></label>
<label>Priority<select name="priority"><option value="normal" @selected(old('priority',$order->priority?:'normal')==='normal')>Normal</option><option value="urgent" @selected(old('priority',$order->priority)==='urgent')>Urgent</option><option value="high" @selected(old('priority',$order->priority)==='high')>High</option></select></label>
<label>Fulfillment<select name="fulfillment_type" data-fulfillment-type><option value="delivery" @selected(old('fulfillment_type',$order->fulfillment_type?:'delivery')==='delivery')>Delivery</option><option value="pickup" @selected(old('fulfillment_type',$order->fulfillment_type)==='pickup')>Pickup from store</option></select></label>
<label class="check"><input type="hidden" name="is_very_urgent" value="0"><input type="checkbox" name="is_very_urgent" value="1" @checked(old('is_very_urgent',$order->is_very_urgent))> Mark very urgent</label>
<label class="span-2">Delivery address<textarea name="delivery_address" data-customer-address>{{ old('delivery_address',$order->delivery_address) }}</textarea></label>
</div></div>
<div class="card" style="margin-top:18px"><div class="card-header"><h2>Order items</h2><div class="header-actions"><button type="button" class="btn small" data-add-row>+ Add product</button><button type="button" class="btn small" data-add-manual-row>+ Add manual line</button><button type="button" class="btn small" data-open-dialog="quick-product">+ New product</button></div></div>
<div class="table-wrap items-table-wrap"><table id="order-items"><thead><tr><th>Product name</th><th>Qty</th><th>Price</th><th>VAT %</th><th>Customisation</th><th>Total</th><th></th></tr></thead><tbody>
@foreach($lines as $index=>$line)
@if($line['is_manual']??false)
<tr data-product-row><td><input type="text" name="items[{{ $index }}][description]" value="{{ $line['description']??'' }}" placeholder="Description (e.g. Fixing charge)" required><input type="hidden" name="items[{{ $index }}][product_id]" value=""></td><td><input data-qty name="items[{{ $index }}][qty]" type="number" step=".001" min=".001" value="{{ $line['qty']??1 }}"></td><td><input data-price name="items[{{ $index }}][unit_price]" type="number" step=".01" min="0" value="{{ $line['unit_price']??0 }}"></td><td><input data-tax name="items[{{ $index }}][tax_rate]" type="number" step=".01" min="0" value="{{ $line['tax_rate']??5 }}"></td><td><input name="items[{{ $index }}][customisation]" value="{{ $line['customisation']??'' }}"></td><td data-line-total class="amount">0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr>
@else
<tr data-product-row><td><div class="combo-input-row"><div class="combo"><input type="text" data-product-combo-input autocomplete="off" placeholder="Search name or SKU..." name="items[{{ $index }}][product_label]" value="{{ $line['product_label']??'' }}" required><div class="combo-results" data-product-combo-results></div></div><input type="hidden" name="items[{{ $index }}][product_id]" data-product-combo-id value="{{ $line['product_id']??'' }}"></div></td><td><input data-qty name="items[{{ $index }}][qty]" type="number" step=".001" min=".001" value="{{ $line['qty']??1 }}"></td><td><input data-price name="items[{{ $index }}][unit_price]" type="number" step=".01" min="0" value="{{ $line['unit_price']??0 }}"></td><td><input data-tax name="items[{{ $index }}][tax_rate]" type="number" step=".01" min="0" value="{{ $line['tax_rate']??5 }}"></td><td><input name="items[{{ $index }}][customisation]" value="{{ $line['customisation']??'' }}"></td><td data-line-total class="amount">0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr>
@endif
@endforeach
</tbody>
<template data-row-template><tr data-product-row><td><div class="combo-input-row"><div class="combo"><input type="text" data-product-combo-input autocomplete="off" placeholder="Search name or SKU..." name="items[__INDEX__][product_label]" required><div class="combo-results" data-product-combo-results></div></div><input type="hidden" name="items[__INDEX__][product_id]" data-product-combo-id value=""></div></td><td><input data-qty name="items[__INDEX__][qty]" type="number" step=".001" min=".001" value="1"></td><td><input data-price name="items[__INDEX__][unit_price]" type="number" step=".01" min="0" value="0"></td><td><input data-tax name="items[__INDEX__][tax_rate]" type="number" step=".01" min="0" value="5"></td><td><input name="items[__INDEX__][customisation]"></td><td data-line-total class="amount">0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr></template>
<template data-manual-row-template><tr data-product-row><td><input type="text" name="items[__INDEX__][description]" placeholder="Description (e.g. Fixing charge)" required><input type="hidden" name="items[__INDEX__][product_id]" value=""></td><td><input data-qty name="items[__INDEX__][qty]" type="number" step=".001" min=".001" value="1"></td><td><input data-price name="items[__INDEX__][unit_price]" type="number" step=".01" min="0" value="0"></td><td><input data-tax name="items[__INDEX__][tax_rate]" type="number" step=".01" min="0" value="5"></td><td><input name="items[__INDEX__][customisation]"></td><td data-line-total class="amount">0.00</td><td><button type="button" class="btn small" data-remove-row>×</button></td></tr></template>
</table></div>
<div class="summary" style="margin-top:15px"><div><small>Subtotal</small><strong>AED <span data-subtotal>0.00</span></strong></div><div><small>VAT</small><strong>AED <span data-tax-total>0.00</span></strong></div><div><small>Total</small><strong>AED <span data-grand-total>0.00</span></strong></div></div>
<label style="margin-top:15px">Notes<textarea name="notes">{{ old('notes',$order->notes) }}</textarea></label><div class="actions"><a class="btn" href="{{ $order->exists?route('orders.show',$order):route('orders.index') }}">Cancel</a><button class="btn primary">{{ $order->exists?'Update order & schedule':'Create order & add to schedule' }}</button></div></div></form>

<dialog id="quick-customer" class="quick-dialog"><form data-quick-customer-form><div class="dialog-head"><h2>Add customer</h2><button type="button" class="dialog-close" data-close-dialog>×</button></div><div class="form-grid"><label>Name<input name="name" required></label><label>Phone<input name="phone" placeholder="+971..." required></label><label>Location<select name="emirate"><option value="">Select</option>@foreach($locations as $location)<option>{{ $location }}</option>@endforeach</select></label><label>Area<input name="area"></label><label class="span-2">Delivery address<textarea name="delivery_address"></textarea></label></div><p class="form-error" data-form-error></p><div class="actions"><button type="button" class="btn" data-close-dialog>Cancel</button><button type="submit" class="btn primary">Save and select</button></div></form></dialog>
<dialog id="quick-product" class="quick-dialog"><form data-quick-product-form enctype="multipart/form-data"><div class="dialog-head"><h2>Add product</h2><button type="button" class="dialog-close" data-close-dialog>×</button></div><div class="form-grid">@include('products._fields', ['product' => new \App\Models\Product, 'categories' => $productCategories, 'taxRates' => $productTaxRates, 'fieldPrefix' => null])</div><p class="form-error" data-form-error></p><div class="actions"><button type="button" class="btn" data-close-dialog>Cancel</button><button type="submit" class="btn primary">Save and select</button></div></form></dialog>
@endsection
@push('scripts')<script src="{{ asset('build/assets/order-entry.js') }}?v={{ @filemtime(public_path('build/assets/order-entry.js')) ?: time() }}" defer></script>@endpush
