@extends('layouts.app')
@section('title','Sales Orders')
@section('subtitle','Create, edit and track all commercial orders')
@section('content')
@include('partials._saved-filters', ['page' => 'orders'])
<div class="toolbar"><form><input name="q" value="{{ request('q') }}" placeholder="Order, customer or phone"><input type="month" name="month" value="{{ request('month') }}"><select name="delivery_status"><option value="">All delivery statuses</option>@foreach(['not_scheduled','scheduled','out_for_delivery','delivered','failed','returned'] as $status)<option value="{{ $status }}" @selected(request('delivery_status')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><label class="check"><input type="checkbox" name="show_legacy" value="1" @checked(request()->boolean('show_legacy'))>Include imported delivery history</label><button class="btn">Filter</button></form>@if(auth()->user()->hasPermission('orders.manage'))<a class="btn primary" href="{{ route('orders.create') }}">+ New sales order</a>@endif</div>
@if(request()->query())<form method="post" action="{{ route('saved-filters.store') }}" style="margin-bottom:15px">@csrf<input type="hidden" name="page" value="orders">@foreach(request()->query() as $k=>$v)<input type="hidden" name="params[{{ $k }}]" value="{{ $v }}">@endforeach<input name="name" placeholder="Save this filter as..." style="width:220px;display:inline-block"><button class="btn small">Save filter</button></form>@endif
<div class="table-wrap mobile-cards"><table><thead><tr><th>Order</th><th>Customer</th><th>Order date</th><th>Delivery</th><th>Status</th><th>Fulfillment</th><th>Total</th><th>Paid</th><th>Remaining</th><th>Payment status</th><th>Actions</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td data-label="Order"><a href="{{ route('orders.show',$order) }}"><b>{{ $order->order_number }}</b></a>@if($order->is_legacy_delivery_import)<span class="badge">Delivery history</span>@elseif($order->is_very_urgent)<span class="badge red">Very urgent</span>@endif @unless($order->is_legacy_delivery_import)@include('partials._confirmed-proof-widget',['order'=>$order])@endunless</td><td data-label="Customer">{{ $order->customer->name }}<div class="muted">{{ $order->customer_phone?:$order->customer->phone }} · {{ $order->emirate }}</div></td><td data-label="Order date">{{ $order->order_date->format('d M Y') }}</td><td data-label="Delivery">{{ $order->delivery_date?->format('d M Y')??'Not set' }}</td><td data-label="Status"><span class="badge {{ ['pending'=>'amber','ready'=>'blue','delivered'=>'green','canceled'=>'red'][$order->simple_status] ?? 'amber' }}">{{ ucfirst($order->simple_status) }}</span> @if(!$order->is_legacy_delivery_import&&in_array($order->simple_status,['ready','delivered']))<button type="button" class="btn small success" data-whatsapp-share data-check-url="{{ route('whatsapp.check',$order) }}" data-link-url="{{ route('whatsapp.link',$order) }}" title="Share via WhatsApp" style="padding:2px 7px">💬</button>@endif</td><td data-label="Fulfillment">{{ $order->fulfillment_type==='pickup' ? 'Pickup' : ($order->driver?->name ?? 'Delivery — unassigned') }}</td><td data-label="Total" class="amount">@if($order->is_legacy_delivery_import)<span class="muted">Not imported</span>@else AED {{ number_format($order->grand_total,2) }}@endif</td><td data-label="Paid" class="amount kpi-good">@if(!$order->is_legacy_delivery_import)AED {{ number_format($order->paid_amount,2) }}@endif</td><td data-label="Remaining" class="amount kpi-bad">@if(!$order->is_legacy_delivery_import)AED {{ number_format($order->remaining_amount,2) }}@endif</td><td data-label="Payment status">@unless($order->is_legacy_delivery_import)<span class="badge {{ $order->computed_payment_status==='paid'?'green':($order->computed_payment_status==='partially_paid'?'amber':'red') }}">{{ str($order->computed_payment_status)->replace('_',' ') }}</span>@endunless</td><td data-label="Actions"><div class="row-actions"><a class="btn small" href="{{ route('orders.show',$order) }}">Open</a>@if(!$order->is_legacy_delivery_import&&auth()->user()->hasPermission('orders.manage'))<a class="btn small primary" href="{{ route('orders.edit',$order) }}">Edit</a>@endif</div></td></tr>
@empty<tr><td colspan="11" class="empty">No sales orders found.</td></tr>@endforelse
</tbody></table></div>{{ $orders->links() }}
@endsection
