@extends('layouts.app')
@section('title','Sales Orders')
@section('subtitle','Create, edit and track all commercial orders')
@section('content')
<div class="toolbar"><form><input name="q" value="{{ request('q') }}" placeholder="Order, customer or phone"><input type="month" name="month" value="{{ request('month') }}"><select name="delivery_status"><option value="">All delivery statuses</option>@foreach(['not_scheduled','scheduled','out_for_delivery','delivered','failed','returned'] as $status)<option value="{{ $status }}" @selected(request('delivery_status')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select><label class="check"><input type="checkbox" name="show_legacy" value="1" @checked(request()->boolean('show_legacy'))>Include imported delivery history</label><button class="btn">Filter</button></form>@if(auth()->user()->hasPermission('orders.manage'))<a class="btn primary" href="{{ route('orders.create') }}">+ New sales order</a>@endif</div>
<div class="table-wrap mobile-cards"><table><thead><tr><th>Order</th><th>Customer</th><th>Order date</th><th>Delivery</th><th>Confirmation</th><th>Design</th><th>Production</th><th>Delivery status</th><th>Total</th><th>Paid</th><th>Remaining</th><th>Payment status</th><th>Actions</th></tr></thead><tbody>
@forelse($orders as $order)<tr><td data-label="Order"><a href="{{ route('orders.show',$order) }}"><b>{{ $order->order_number }}</b></a>@if($order->is_legacy_delivery_import)<span class="badge">Delivery history</span>@elseif($order->is_very_urgent)<span class="badge red">Very urgent</span>@endif</td><td data-label="Customer">{{ $order->customer->name }}<div class="muted">{{ $order->customer_phone?:$order->customer->phone }} · {{ $order->emirate }}</div></td><td data-label="Order date">{{ $order->order_date->format('d M Y') }}</td><td data-label="Delivery">{{ $order->delivery_date?->format('d M Y')??'Not set' }}</td><td data-label="Confirmation"><span class="badge amber">{{ str($order->confirmation_status)->replace('_',' ') }}</span></td><td data-label="Design"><span class="badge blue">{{ str($order->design_status)->replace('_',' ') }}</span></td><td data-label="Production"><span class="badge">{{ str($order->production_status)->replace('_',' ') }}</span></td><td data-label="Delivery status"><span class="badge {{ $order->delivery_status==='delivered'?'green':'' }}">{{ str($order->delivery_status)->replace('_',' ') }}</span></td><td data-label="Total" class="amount">@if($order->is_legacy_delivery_import)<span class="muted">Not imported</span>@else AED {{ number_format($order->grand_total,2) }}@endif</td><td data-label="Paid" class="amount kpi-good">@if(!$order->is_legacy_delivery_import)AED {{ number_format($order->paid_amount,2) }}@endif</td><td data-label="Remaining" class="amount kpi-bad">@if(!$order->is_legacy_delivery_import)AED {{ number_format($order->remaining_amount,2) }}@endif</td><td data-label="Payment status">@unless($order->is_legacy_delivery_import)<span class="badge {{ $order->computed_payment_status==='paid'?'green':($order->computed_payment_status==='partially_paid'?'amber':'red') }}">{{ str($order->computed_payment_status)->replace('_',' ') }}</span>@endunless</td><td data-label="Actions"><div class="row-actions"><a class="btn small" href="{{ route('orders.show',$order) }}">Open</a>@if(!$order->is_legacy_delivery_import&&auth()->user()->hasPermission('orders.manage'))<a class="btn small primary" href="{{ route('orders.edit',$order) }}">Edit</a>@endif</div></td></tr>
@empty<tr><td colspan="13" class="empty">No sales orders found.</td></tr>@endforelse
</tbody></table></div>{{ $orders->links() }}
@endsection
